name: Keep Render Awake

on:
  schedule:
    # Every 10 minutes between 22:30–23:59 UTC (midnight at 4–5:29 IST)
    - cron: "*/10 22,23 * * *"
    # Every 10 minutes between 00:00–17:30 UTC (05:30–23:00 IST)
    - cron: "*/10 0-17 * * *"

  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render server
        run: |
          curl -m 20 https://attendance-4rm8.onrender.com/today-logins || echo "Ping failed"
